#Eureka configuration
   
eureka:
  instance:
     ip-address: true 
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}    
           
okta:
    oauth2:
      issuer: https://dev-46592315.okta.com/oauth2/default  
      audience: api://default
